### ISSUE TITLE
Use Fedora Devel list as the example dataset

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/mailing-list-analysis-toolkit#2]
Use [Fedora Devel](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/) list as the example dataset

**Comment by tumido** [comment]
I think we can close this one now, is that right @MichaelClifford ? :slightly_smiling_face:

**Comment by MichaelClifford** [comment]
@tumido This issue is so closed! :partying_face:
