### ISSUE TITLE
Hatesonar dependency issue

### ISSUE THREAD

**Issue by cdolfi** [aicoe-aiops/mailing-list-analysis-toolkit#52]
**Describe the bug**
Hatesonar does not support python 3.8 and has package dependencies on some old version of packages like scikit-learn. Looking for suggestions on how to install hatsonar in the currect 

I am trying to use hatesonar as a baseline to analyze hate speech. I am looking for suggestions about how to install hatesonar in the current environment given that it is 3.8 and hatesonar does not support the required python version. This most likely will not be the final approach so this does not need to go into production. With that, I need to be able to try this out since this is a well known open source package and seems like a good approach to start with to compare future approaches with.

**Comment by goern** [comment]
/kind question

@fridex good advise on this one?

**Comment by fridex** [comment]
@cdolfi not sure if the package will work in 3.7+ environments as it officially supports python 3.6 - it might require some code changes. Any reason not to use python 3.6?

**Comment by tumido** [comment]
looking at our current dep stack, I don't think there's any reason to require 3.8. I don't see a problem with downgrading to 3.6 for this, :slightly_smiling_face:

**Comment by oindrillac** [comment]
@tumido so to put that into effect, is making the change `python_version = "3.6"` in the Pipfile followed by a `pipenv install` is all that is needed?

**Comment by fridex** [comment]
You will also need to clean the old virtual environment:

```
cd directory/
pipenv --rm
sed -i 's/python_version = "3.8"/python_version = "3.6"/' Pipfile
pipenv install --python 3.6
```

**Comment by tumido** [comment]
We'll also need to change the .aicoe build config's base image

https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/blob/fe651caff884945d8f70db8cf1942491b2983ac4/.aicoe-ci.yaml#L10

I'll prepare a PR.

**Comment by MichaelClifford** [comment]
@tumido @fridex Thanks for the advice on this issue. I have two questions about how to handle this situation in the future.

> looking at our current dep stack, I don't think there's any reason to require 3.8. I don't see a problem with downgrading to 3.6 for this 

I think it would be better to not rely on a human to check the dep stack :smile: for these kinds of changes as this may impact another notebook in this repo (also its probably tedious). Would it make sense to have a test as part of the CI process that would run all the import statements in the notebooks to confirm this kind of changes really does not break anything?  

The second thought is that once we move to the Elyra based requirements-per-notebook approach that Francesco has been working on, this issue would no longer exist, correct? As this notebook would have a completely separate list of requirements? 

thanks!

**Comment by tumido** [comment]
@MichaelClifford 

> The second thought is that once we move to the Elyra based requirements-per-notebook approach that Francesco has been working on, this issue would no longer exist, correct? As this notebook would have a completely separate list of requirements?

Correct. Once we build an image runtime per notebook and the requirements are specified by the notebook itself (each notebook has it's own inline Pipfile), this issue no longer exists.
